### ISSUE TITLE
Take length comps out of single area EM

### ISSUE THREAD

**Issue by khfenske** [khfenske/Sablefish_ApportionmentStrategies#11]
Task - take the length comps out of the single area EM. Prefer they are commented out rather than removed entirely in case we want to add them back in later.  The single area EM files are in the ADMB folder.

**Comment by khfenske** [comment]
I have put the length comp weights at 0 in the .ctl file. Is this the correct way to remove them without removing them?

**Comment by GreatDana** [comment]
Yes! And its sometimes nice to look how well the comps fit without fitting
them.
