### ISSUE TITLE
can't get the F estimation function to work

### ISSUE THREAD

**Issue by khfenske** [khfenske/Sablefish_ApportionmentStrategies#17]
I have a function called calc_init_Fs2.R that is called from calc_init_pop, which is in turn called in Run-Sablefish-Sim.R.  The first function is supposed to solve for the F (called Fa because it used to be F at age but now is just F not by age) that makes FixTr_catch best match obs_catch.  But it's not running, even when I try testing the 'inner most' function (calc_init_Fs2). I am thinking that it could be an issue with how i'm trying to call in the necessary 'data' or perhaps with indexing across dimensions. I'm not sure what else to try, so if either of you have time to take a look please feel free. All this in the in branch 12-6-18, not on the master.

**Comment by curryc2** [comment]
Kari,

I’ll take a look over the next few days. 

Cheers,

Curry

> On Dec 21, 2018, at 6:53 PM, Kari Fenske <notifications@github.com> wrote:
> 
> at makes FixTr_catch best match obs_catch.

Curry J. Cunningham, Ph.D.
(907) 360.4217
Website: currycunningham.com/
Twitter: @CurryCunningham

**Comment by curryc2** [comment]
There is now a function `estimate_Fmort4catch()` that estimates the instantaneous fishing mortality rate (not age-specific) that will result in a specified target catch biomass, given attributes of the population and specific fishing fleet/gear. The `catch` argument to this function is that target, and will be an output of the apportionment rule. Other attributes of this function are `temp.selex` the selectivity of the fleet/gear, `temp.N` the abundance (from the previous year) by sex and age, `wa` weight@age by sex, `mx` the natural mortality rate at age by sex, and `bisection` indicating whether the instantaneous fishing mortality rate that results in catch equal to the target will be estimated iteratively via bisection or using `optimize()` if `bisection=FALSE`. Note that the `estimate_Fmort4catch()` depends on the `convert_Fmort2catch()` function.
