### ISSUE TITLE
Get the RE apportionment to work on real data

### ISSUE THREAD

**Issue by khfenske** [khfenske/Sablefish_ApportionmentStrategies#5]
In the ApportionmentAppliedTo2017Data file.

**Comment by khfenske** [comment]
@GreatDana  Hey - can you pull the most recent ApportionmentAppliedTo2017Data file and see if you can get the RE model to run for you? I broke it up so that the re_apportionment function is only running the RE model for now, as a first try to get it to run. But it's still not running and I'm stuck.

**Comment by GreatDana** [comment]
@khfenske It doesn't seem like you pushed up the data files unless I'm not seeing it right.
